POST https://node-do-zero-oumf.onrender.com/videos
Content-Type: application/json

{
  "title": "video Node",
  "description": "Description video Node", 
  "duration": "120" 
}

###

GET https://node-do-zero-oumf.onrender.com/videos

###

PUT https://node-do-zero-oumf.onrender.com/videos/a532d130-76f8-4520-a45f-98f956018324
Content-Type: application/json

{
  "title": "video 02",
  "description": "Description Node", 
  "duration": "122" 
}

###

DELETE  https://node-do-zero-oumf.onrender.com/videos/6a3029aa-28b5-46db-8cc4-2e18c00dccb5
